// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ROtgkGMcxLM1jAMVl3RzaamXSh5tHHc',
    appId: '1:641996344203:web:e3600e259779f3ede67d8e',
    messagingSenderId: '641996344203',
    projectId: 'aybook-a69fd',
    authDomain: 'aybook-a69fd.firebaseapp.com',
    storageBucket: 'aybook-a69fd.firebasestorage.app',
    measurementId: 'G-S5TRBRHQJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmgNFgSr31TrG139tzDSHjg9AK6AtScM0',
    appId: '1:641996344203:android:e7d98a3102f417dee67d8e',
    messagingSenderId: '641996344203',
    projectId: 'aybook-a69fd',
    storageBucket: 'aybook-a69fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjIK7-CoiaqlH0PYhQTRFZoR-NEE2t5f8',
    appId: '1:641996344203:ios:2e7519bf45e2d1dae67d8e',
    messagingSenderId: '641996344203',
    projectId: 'aybook-a69fd',
    storageBucket: 'aybook-a69fd.firebasestorage.app',
    iosBundleId: 'com.example.aybook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjIK7-CoiaqlH0PYhQTRFZoR-NEE2t5f8',
    appId: '1:641996344203:ios:2e7519bf45e2d1dae67d8e',
    messagingSenderId: '641996344203',
    projectId: 'aybook-a69fd',
    storageBucket: 'aybook-a69fd.firebasestorage.app',
    iosBundleId: 'com.example.aybook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ROtgkGMcxLM1jAMVl3RzaamXSh5tHHc',
    appId: '1:641996344203:web:f4756a928771d9a3e67d8e',
    messagingSenderId: '641996344203',
    projectId: 'aybook-a69fd',
    authDomain: 'aybook-a69fd.firebaseapp.com',
    storageBucket: 'aybook-a69fd.firebasestorage.app',
    measurementId: 'G-841KFF7E60',
  );
}
